### PR TITLE
Feat: expose cell builder

### PR DESCRIPTION
**Pull request by LUUUAN**
Expose Cell Builder for customization. This PR contains modification for #202 .

### CODE REVIEW

**Review by paulfitz — APPROVED** [review]
Thank you!

**Comment by LUUUAN** [comment]
@paulfitz Could you publish a new version for this update?

**Comment by ajp-ic-sg** [comment]
@paulfitz Hi, when will this version be released?

**Comment by paulfitz** [comment]
I'm a bit stalled on finding time to rip out `fibers`, not supported by node these days and only there because of how old daff is.

**Pull request merged**
