### PR TITLE
First attempt at a render function

### PR DESCRIPTION
**Pull request by karissa**

### CODE REVIEW

**Comment by karissa** [comment]
Hey @paulfitz , this is a really simple hack and I can't actually test it because apparently I can't compile Haxe on my machine!

**Comment by paulfitz** [comment]
Thanks a lot @karissa! What do you think of these tweaks? ec7dcd678fcbc892838564cfa03dbe7051abd6ff  I thought maybe it'd be better to separate out html vs ansi text, since a lot of users won't ever have come across the console stuff and will be looking for the html.

Does apt-get/brew install haxe not work? What goes wrong?

**Comment by karissa** [comment]
Woo @paulfitz ! nice! :) yeah, your tweaks make sense.

When I do:
```
$ brew install haxe
haxe: OS X Mavericks or older is required.
Error: An unsatisfied requirement failed this build.
```

**Comment by paulfitz** [comment]
@karissa does `brew install haxe --HEAD` do any better? Other possible soln at https://github.com/HaxeFoundation/neko/issues/44#issuecomment-84437956

**Comment by karissa** [comment]
yeah that seemed to have gotten me there! Woo!

On Thu, Apr 23, 2015 at 7:24 AM, Paul Fitzpatrick <notifications@github.com>
wrote:

> @karissa <https://github.com/karissa> does brew install haxe --HEAD do
> any better? Other possible soln at HaxeFoundation/neko#44 (comment)
> <https://github.com/HaxeFoundation/neko/issues/44#issuecomment-84437956>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulfitz/daff/pull/26#issuecomment-95603632>.
>



-- 
Karissa McKelvey
karissamck.com

Dat dat-data.com
U.S Open Data usopendata.org
Debt Collective debtcollective.org
Taskforce taskforce.is
Brass Liberation Orchestra brassliberation.org

**Pull request closed without merging**
